name: Deploy to All-Inkl

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  build-and-deploy:
    name: Build, and deploy to All-Inkl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: |
          npm ci

      - name: Build code
        run: |
          npm run build

      - name: Deploy to All-Inkl
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASSWORD }}
          local-dir: './src/.vuepress/dist/'
